### ISSUE TITLE
Break-up training into smaller stages

### ISSUE THREAD

**Issue by mcqueen256** [CoEDL/elpis#31]
The current stages for training include:
`untrained`
`training`
`trained`

However, `training` can be broken down into the headers found in kaldi-helpers/.../run.sh

**Comment by nicklambourne** [comment]
Potential Approach:
- Each command or command group in gmm-decode-long.sh should be broken into its own script, then all scripts put inside a "stages" directory using the naming convention `0_stageOneName.sh`. 
- Script modified to call each of them instead of a single one.
- State variable `current_stage` introduced and updated at each stage.
- Status endpoint returns current stage + dictionary of logs for each stage.'
- Front end reports stages, with collapsed sections for each stage's log output.
- Each stage is displayed in front end, currently running one shows loading symbol, stages not yet reached are greyed out.
