### ISSUE TITLE
Select Elan data by top-most tier, tier name, or tier type

### ISSUE THREAD

**Issue by benfoley** [CoEDL/elpis#36]
Design GUI and API methods to select Elan data by tier number rather than name.

**Comment by nikopartanen** [comment]
In the tier structure used in my research projects we have the top-most tier used for utterance's reference-id, and the transcriptions are one level below that. However, we may be in minority here, and maybe it is most common to have them on top-most tier.

One solution could be to specify the tier type, so that for example all transcriptions would be on tier type "transcription", whereas the tier names would be something like "transcription@speaker1", "transcription@speaker2" etc. So tier names, usually, are different in each file and for each speaker, but one would assume they always have the same type across ELAN corpus. I believe this kind of use of tier types is very common in language documentation.

**Comment by benfoley** [comment]
Hi Niko, thanks for the info. Selection by type would be a good option, as well as a numbered selection. It’s amazing how much diversity there is in the way that people set up their tiers!
Ben

**Comment by benfoley** [comment]
note to self: look at the elan splitter repo for args and method

**Comment by nikopartanen** [comment]
Hi Ben! Yes, the diversity of tier setups is impossible to deal with. Also, very strangely, it seems that lots of tier setups still are designed for one speaker only, which allows tier names just as "Phrase". With more speakers this would never work, but the different speakers would need some convention to make tier names unique.

**Comment by benfoley** [comment]
Look for common tier type and tier name, suggest (one) as the default

**Comment by benfoley** [comment]
Closed with #84
